export enum ENV {
  PORT = "PORT",
  NODE_ENV = "NODE_ENV",
  JWT_SECRET_KEY = "JWT_SECRET_KEY",
  SERVER_URL = "SERVER_URL",
  DATABASE_URL = "DATABASE_URL",
  DIRECT_URL = "DIRECT_URL",
  CLOUDINARY_CLOUD_NAME = "CLOUDINARY_CLOUD_NAME",
  CLOUDINARY_API_KEY = "CLOUDINARY_API_KEY",
  CLOUDINARY_API_SECRET = "CLOUDINARY_API_SECRET",
}
