export enum ENV {
  DATABASE_URL = "DATABASE_URL",
  DIRECT_URL = "DIRECT_URL",
  CLIENT_URL = "CLIENT_URL",
  SERVER_URL = "SERVER_URL",
  NODE_ENV = "NODE_ENV",
  JWT_SECRET_KEY = "JWT_SECRET_KEY",
  PORT = "PORT",
}
